### ISSUE TITLE
Server Fails to Start in Docker Due to Segmentation Fault

### ISSUE THREAD

**Issue by sumia01** [joedwards32/CS2#49] opened 2023-11-03 16:14 UTC
Hi,

I'm trying to start the server in docker but it's not working :(
See below the full output log & some system info.

- AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx
- 16GB RAM

I hope you can give me some advice to make this server working.

<details>
  <summary>Click here for log output</summary>

```
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Downloading update (50 of 59,532 KB)...
[  0%] Downloading update (1,444 of 59,532 KB)...
[  2%] Downloading update (5,329 of 59,532 KB)...
[  8%] Downloading update (7,618 of 59,532 KB)...
[ 12%] Downloading update (10,513 of 59,532 KB)...
[ 17%] Downloading update (13,261 of 59,532 KB)...
[ 22%] Downloading update (15,511 of 59,532 KB)...
[ 26%] Downloading update (18,271 of 59,532 KB)...
[ 30%] Downloading update (20,776 of 59,532 KB)...
[ 34%] Downloading update (23,281 of 59,532 KB)...
[ 39%] Downloading update (25,795 of 59,532 KB)...
[ 43%] Downloading update (28,049 of 59,532 KB)...
[ 47%] Downloading update (30,304 of 59,532 KB)...
[ 50%] Downloading update (32,940 of 59,532 KB)...
[ 55%] Downloading update (35,454 of 59,532 KB)...
[ 59%] Downloading update (37,967 of 59,532 KB)...
[ 63%] Downloading update (40,044 of 59,532 KB)...
[ 67%] Downloading update (42,057 of 59,532 KB)...
[ 70%] Downloading update (43,317 of 59,532 KB)...
[ 72%] Downloading update (44,574 of 59,532 KB)...
[ 74%] Downloading update (45,818 of 59,532 KB)...
[ 76%] Downloading update (47,091 of 59,532 KB)...
[ 79%] Downloading update (48,340 of 59,532 KB)...
[ 81%] Downloading update (49,584 of 59,532 KB)...
[ 83%] Downloading update (50,833 of 59,532 KB)...
[ 85%] Downloading update (52,209 of 59,532 KB)...
[ 87%] Downloading update (53,457 of 59,532 KB)...
[ 89%] Downloading update (54,702 of 59,532 KB)...
[ 91%] Downloading update (55,967 of 59,532 KB)...
[ 94%] Downloading update (57,211 of 59,532 KB)...
[ 96%] Downloading update (58,468 of 59,532 KB)...
[ 98%] Downloading update (59,532 of 59,532 KB)...
[100%] Downloading update (59,532 of 59,532 KB)...
[100%] Download complete.
[----] Installing update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
Logging directory: '/home/steam/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1698778122
-- type 'quit' to exit --
Loading Steam API...OK
Logging in user '' to Steam Public...
password: FAILED (Invalid Password)
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libengine2.so, got 0x55beacc734d0
Using breakpad crash handler
Setting breakpad minidump AppID = 2347773
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Console initialized.
Steam AppId(730), BreakpadId(2347771)
InitSteamLogin_Internal: Initializing breakpad.
Steam Universe is invalid, possibly asking before Steam was successfully initialized.
ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
ResetBreakpadAppId: Setting dedicated server app id: 2347773
Loaded libSDL3.so.0, got 0x55beacd72ff0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libtier0.so, got 0x55beacc5d290
Visibility enabled.
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x55beacd734b0
USRLOCAL path not found!
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/liblocalize.so, got 0x55beacd859e0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/librendersystemempty.so, got 0x55beacd97ae0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x55beacdaa010
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libschemasystem.so, got 0x55beacdbc110
Trying to set dxlevel (111) which is higher than the card can support (110)!
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libmaterialsystem2.so, got 0x55beacdce630
---------------
Path ID:             File Path:
ADDONS               "/home/steam/cs2-dedicated/game/csgo_addons/" 
CONTENT              "/home/steam/cs2-dedicated/content/csgo/" 
CONTENT              "/home/steam/cs2-dedicated/content/csgo_imported/" 
CONTENT              "/home/steam/cs2-dedicated/content/csgo_core/" 
CONTENT              "/home/steam/cs2-dedicated/content/core/" 
CONTENTADDONS        "/home/steam/cs2-dedicated/content/csgo_addons/" 
CONTENTROOT          "/home/steam/cs2-dedicated/content/" 
DEFAULT_WRITE_PATH   "/home/steam/cs2-dedicated/game/csgo/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo/pak01.vpk
DEFAULT_WRITE_PATH   "/home/steam/cs2-dedicated/game/csgo/" 
EXECUTABLE_PATH      "/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/" 
GAME                 "/home/steam/cs2-dedicated/game/csgo/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo/pak01.vpk
GAME                 "/home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk
GAME                 "/home/steam/cs2-dedicated/game/csgo_core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_core/pak01.vpk
GAME                 "/home/steam/cs2-dedicated/game/core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/core/pak01.vpk
GAME                 "/home/steam/cs2-dedicated/game/csgo/" 
GAME                 "/home/steam/cs2-dedicated/game/csgo_imported/" 
GAME                 "/home/steam/cs2-dedicated/game/csgo_core/" 
GAME                 "/home/steam/cs2-dedicated/game/core/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo/bin/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_imported/bin/linuxsteamrt64/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_imported/bin/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_core/bin/linuxsteamrt64/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/csgo_core/bin/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/core/bin/linuxsteamrt64/" 
GAMEBIN              "/home/steam/cs2-dedicated/game/core/bin/" 
GAMEROOT             "/home/steam/cs2-dedicated/game/" 
MOD                  "/home/steam/cs2-dedicated/game/csgo/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo/pak01.vpk
MOD                  "/home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_imported/pak01.vpk
MOD                  "/home/steam/cs2-dedicated/game/csgo_core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/csgo_core/pak01.vpk
MOD                  "/home/steam/cs2-dedicated/game/csgo/" 
MOD                  "/home/steam/cs2-dedicated/game/csgo_imported/" 
MOD                  "/home/steam/cs2-dedicated/game/csgo_core/" 
PLATFORM             "/home/steam/cs2-dedicated/game/core/pak01.vpk" (vpk) /home/steam/cs2-dedicated/game/core/pak01.vpk
PLATFORM             "/home/steam/cs2-dedicated/game/core/" 
SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo/" 
SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo_imported/" 
SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/csgo_core/" 
SHADER_SOURCE        "/home/steam/cs2-dedicated/src/shaders/core/" 
SHADER_SOURCE_MOD    "/home/steam/cs2-dedicated/src/shaders/csgo/" 
SHADER_SOURCE_ROOT   "/home/steam/cs2-dedicated/src/shaders/" 
command line arguments:
-dedicated -ip -port 27015 -console -usercon -maxplayers 18 +game_alias competitive +mapgroup mg_active +map de_inferno
protected command line arguments (stripped from above):
+rcon_password <protected> +sv_password <protected>
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libmeshsystem.so, got 0x55beacde0b50
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libworldrenderer.so, got 0x55beacdf3070
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libpulse_system.so, got 0x55beace059b0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libvscript.so, got 0x55beace1a390
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libnetworksystem.so, got 0x55beace2c490
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libanimationsystem.so, got 0x55beace40690
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libvphysics2.so, got 0x55beace56990
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libsoundsystem.so, got 0x55beace696f0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libscenesystem.so, got 0x55beace7f9f0
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libv8system.so, got 0x55beace94c70
Network System Initialized
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so, got (nil)
 failed to dlopen /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so error=/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
Loaded libserver_valve.so, got (nil)
 failed to dlopen "/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so" error=/home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
 failed to dlopen "libserver_valve.so" error=libserver_valve.so: cannot open shared object file: No such file or directory
 failed to dlopen libserver_valve.so error=libserver_valve.so: cannot open shared object file: No such file or directory
Loaded /home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/libserver.so, got 0x55beaceaeea0
Physics Console Communications is not initialized
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libengine2.so, got 0x55beacc734d0
Loaded /home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/libhost.so, got 0x55beacedf660
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libscenefilecache.so, got 0x55beacef2c00
Loaded /home/steam/cs2-dedicated/game/bin/linuxsteamrt64/libparticles.so, got 0x55beacf04d00
Loaded /home/steam/cs2-dedicated/game/csgo/bin/linuxsteamrt64/libmatchmaking.so, got 0x55beacf186c0
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 730
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
[S_API FAIL] Tried to access Steam interface SteamUtils010 before SteamAPI_Init succeeded.
Setting breakpad minidump AppID = 2347773
No .vcds loaded or no scenes/scenes.vrman
GameTypes: missing mapgroupsSP entry for game type/mode (custom/custom).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/cooperative).
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
Event System loaded 93 events from file: vpk:/home/steam/cs2-dedicated/game/core/pak01.vpk:resource/core.gameevents.
Event System loaded 50 events from file: vpk:/home/steam/cs2-dedicated/game/csgo/pak01.vpk:resource/game.gameevents.
Event System loaded 152 events from file: vpk:/home/steam/cs2-dedicated/game/csgo/pak01.vpk:./resource/mod.gameevents.
CEntitySystem::BuildEntityNetworking (parallel build of server) took 112.442 msecs for 218 out of 297 classes
[STARTUP] {0.858} server module init ok
CHostStateMgr::QueueNewRequest( Idle (console), 1 )
Source2Init OK
HostStateRequest::Start(HSR_IDLE):  loop(console) id(1) addons() desc(Idle (console))
SwitchToLoop console requested:  id [1] addons []
Host activate: Idle (console)
Game alias "competitive" resolved game type=0 mode=1
Setting mapgroup to 'mg_active'
Loading map "de_inferno"
CHostStateMgr::QueueNewRequest( Loading (de_inferno), 2 )
HostStateRequest::Start(HSR_GAME):  loop(levelload) id(2) addons() desc(Loading (de_inferno))
SwitchToLoop levelload requested:  id [2] addons []
SV:  Level loading started for 'de_inferno'
CL:  CLoopModeLevelLoad::MaybeSwitchToGameLoop switching to "game" loopmode with addons ()
SwitchToLoop game requested:  id [2] addons []
SteamGameServer_Init()
dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
Steam Universe valid after having been requested when invalid.  Universe is now 1
ResetBreakpadAppId: Universe is 1 (k_EUniversePublic)
ResetBreakpadAppId: Setting dedicated server app id: 2347773
SteamGameServer_Init() OK, logging on to Steam
****************************************************
*                                                  *
*  No Steam account token was specified.           *
*  Logging into anonymous game server account.     *
*  Connections will be restricted to LAN only.     *
*                                                  *
*  To create a game server account go to           *
*  http://steamcommunity.com/dev/managegameservers *
*                                                  *
****************************************************
CNetworkSystem::InitGameServer: CSteamGameServerAPIContext::Init OK
Initialized low level socket/threading support.
SDR_LISTEN_PORT is set, but not SDR_CERT/SDR_PRIVATE_KEY.
Set SteamNetworkingSockets P2P_STUN_ServerList to '' as per SteamNetworkingSocketsSerialized
CNetworkGameServerBase::SetServerState (ss_dead -> ss_waitingforgamesessionmanifest)
SV:  maxplayers set to 18
Server is hibernating
ResetGameConVarsToDefaults
Created poll group for socket 'server'
SDR RelayNetworkStatus:  avail=Attempting  config=Attempting  anyrelay=Not Attempted   (Attempt #1 to fetch config (only-if-cached) from https://api.steampowered.com/ISteamApps/GetSDRConfig/v1?appid=730)
AuthStatus (invalid):  Waiting  (Waiting for Steam login)
Network socket 'server' opened on port 27015
Initializing CSGO VScript Game System
SV:  Executing server defaults
SV:  Executing dedicated server config file
[STARTUP] {1.477} created game rules
GameTypes: could not find matching game mode value of "" in any game type.
SV:  CGameRulesGameSystem::GameInit installed game rules
LoadResponseSystem scripts/talker/response_rules.vrr - StartCResponseSystem:  scripts/talker/response_rules.vrr (7681 rules, 811 criteria, and 7681 responses)
LoadResponseSystem scripts/talker/response_rules.vrr - FinishEntry player was not found in surfaceproperties_footsteps.txt
exec: couldn't exec '{*}cfg/skill1.cfg', unable to read file
execing server_default.cfg
execing server.cfg
execing gamemode_competitive.cfg
exec: couldn't exec '{*}cfg/gamemode_competitive_server.cfg', unable to read file
Unknown command 'mp_molotovusedelay'!
Unknown command 'spec_freeze_panel_extended_time'!
Unknown command 'sv_occlude_players'!
Unknown command 'occlusion_test_async'!
Unknown command 'sv_gameinstructor_enable'!
Failed loading resource "models/weapons/v_tablet.vmdl_c" (ERROR_FILEOPEN: File not found)
Failed loading resource "materials/models/player/holiday/santahat.vmat_c" (ERROR_FILEOPEN: File not found)
Failed loading resource "materials/models/player/holiday/facemasks/facemask_battlemask/battlemask.vmat_c" (ERROR_FILEOPEN: File not found)
Model !embedded_sequence_data!characters/models/shared/animsets/animset_t.vmdl: unable to find bone reference "ball_l"
Model !embedded_sequence_data!characters/models/shared/animsets/animset_ct.vmdl: unable to find bone reference "ball_l"
Model !embedded_sequence_data!characters/models/shared/animsets/animset_uiplayer.vmdl: unable to find bone reference "ball_l"
Model models/props/crates/csgo_drop_crate_armsdeal2.vmdl: sequence/animation name collision found "tools_preview"
Model !embedded_sequence_data!characters/models/shared/animsets/animset_ct.vmdl: unable to find bone reference "ball_l"
Model !embedded_sequence_data!characters/models/shared/animsets/animset_uiplayer.vmdl: unable to find bone reference "ball_l"
Model models/props/crates/csgo_drop_crate_bravo.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_winteroffensive.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_phoenix.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_huntsman.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_breakout.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_dangerzone.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_vanguard.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_22.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_23.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_24.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_25.vmdl: sequence/animation name collision found "tools_preview"
material2.cpp(711): Error! Material "materials/error.vmat" doesn't have any valid layers to get the CVsInputSignatureVector from!
material2.cpp(711): Error! Material "materials/error.vmat" doesn't have any valid layers to get the CVsInputSignatureVector from!
Model models/props/crates/csgo_drop_crate_community_26.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_chroma3.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_27.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_28.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_29.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_bloodhound.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_gamma2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_30.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_31.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_glove.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_community_32.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_shadow.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_spectrum.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_hydra.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_revolver.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_spectrum2.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_clutch.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_armsdeal1.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_wildfire.vmdl: sequence/animation name collision found "tools_preview"
Model models/props/crates/csgo_drop_crate_horizon.vmdl: sequence/animation name collision found "tools_preview"
SV:  Spawn Server: de_inferno
CNetworkGameServerBase::SetServerState (ss_waitingforgamesessionmanifest -> ss_loading)
SV:  Connection to Steam servers successful.
SV:  ServerSteamID=[A:1:4258908166:24589] (90177605757159430).
[STARTUP] {4.232} logged on to Steam
Got SDR network config.  Loaded revision 1698875488 OK
SDR RelayNetworkStatus:  avail=Not Attempted  config=OK  anyrelay=Not Attempted   (No need for SDR client network access)
Waited 2.1ms for SteamNetworkingSockets lock [Internal_SDR_LISTEN_PORT]
Gameserver logged on to Steam, assigned identity steamid:90177605757159430
src/steamnetworkingsockets/clientlib/sdr/steamnetworkingsockets_sdr_common.cpp(7061): Assertion Failed: !s_pConfigFetchInProgress
[S_API] SteamAPI_Init(): Loaded local 'steamclient.so' OK.
src/clientcommon/webui_job_dispatcher.cpp (88) : Assertion Failed: WebUI method 'SteamEngine.UpdateTextFilterDictionary#1' has already been registered. Skipping duplicate registration
src/clientcommon/webui_job_dispatcher.cpp (88) : Assertion Failed: WebUI method 'SteamEngine.GetTextFilterDictionary#1' has already been registered. Skipping duplicate registration
src/clientcommon/webui_job_dispatcher.cpp (88) : Assertion Failed: WebUI method 'SteamEngine.GetGameIDForPID#1' has already been registered. Skipping duplicate registration
AuthStatus (steamid:90177605757159430):  Attempting  (Requesting cert)
Set SteamNetworkingSockets P2P_STUN_ServerList to '146.66.155.38:3478' as per SteamNetworkingSocketsSerialized
SV:  VAC secure mode is activated.
AuthStatus (steamid:90177605757159430):  OK  (OK)
Certificate expires in 48h00m at 1699199457 (current time 1699026657), will renew in 46h00m
GC Connection established for server version 2000180, instance idx 1
[STARTUP] {4.712} activated session on GC
CWorldRendererMgr::ServiceWorldRequests long frame: 97.508915ms
Failed loading resource "maps/prefabs/misc/terrorist_team_intro_variant2/world_visibility.vvis_c" (ERROR_FILEOPEN: File not found)
CNetworkGameServerBase::SetServerState (ss_loading -> ss_active)
SV:  IGameSystem::LoopActivateAllSystems {
HO:  IGameSystem::LoopActivateAllSystems {
HO:  } IGameSystem::LoopActivateAllSystems done
SV:  } IGameSystem::LoopActivateAllSystems done
Created physics for de_inferno
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
Cannot create physics for prop_physics "" (models/generic/plants/cress_plant_kit/cress_plant_01_a.vmdl) @{1744.46,1230.74,275.141}
Cannot create physics for prop_physics "" (models/generic/plants/cress_plant_kit/cress_plant_03_a.vmdl) @{1887.22,1230.84,275.628}
Cannot create physics for prop_physics "" (models/generic/plants/cress_plant_kit/cress_plant_03_a.vmdl) @{2140.41,993.081,288.128}
Cannot create physics for prop_physics "" (models/generic/plants/cress_plant_kit/cress_plant_03_a.vmdl) @{2000.41,993.106,288.128}
Cannot create physics for prop_physics "" (models/generic/plants/cress_plant_kit/cress_plant_02_a.vmdl) @{-124.153,-32.1779,157.938}
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
CNavGenParams - Nav mesh requests project default generation parameters but actual parameters
  used during construction differ from defaults. Please re-export the map.
SV:  18 player server started
CSteam3ServerS1::ShutdownGameServer
CNetworkSystem::ShutdownGameServer
Closing 'server' UDP listen socket
Closing 'server' poll group
CNetworkSystem::CleanupDebugOutputFunction()
SteamGameServer_Init()
src/clientcommon/webui_job_dispatcher.cpp (88) : Assertion Failed: WebUI method 'SteamEngine.UpdateTextFilterDictionary#1' has already been registered. Skipping duplicate registration
src/clientcommon/webui_job_dispatcher.cpp (88) : Assertion Failed: WebUI method 'SteamEngine.GetTextFilterDictionary#1' has already been registered. Skipping duplicate registration
CAppInfoCacheReadFromDiskThread took 0 milliseconds to initialize
Setting breakpad minidump AppID = 730
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561197960265728 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561197960265728
Setting breakpad minidump AppID = 2347773
entry.sh: line 62:    46 Segmentation fault      (core dumped) ./cs2 -dedicated -ip -port 27015 -console -usercon -maxplayers 18 +game_alias competitive +mapgroup mg_active +map de_inferno +rcon_password adminpass +sv_password supersecret

```
</details>

**Comment by joedwards32** [comment] 2023-11-03 19:34
Hi @sumia01, 

What container runtime are you using?

What is your host operating system?

Similar segfaults have been observed when there isn't enough memory assigned to the container.

**Comment by daiser** [comment] 2023-11-03 21:20
Hi @joedwards32,

I have same issue.
AMD 5950X
Host: Ubuntu 22.04 (6.2.0 kernel)
Docker engine 24.0.7
Docker compose 2.21.0

Increasing memory limit didn't help.
docker-compose.yaml
```
    deploy:
      resources:
        limits:
          memory: 8G
```

**Comment by joedwards32** [comment] 2023-11-04 08:45
Works for me on:

Host: Ubuntu 22.04 (6.2.0 kernel)
Docker engine: 20.10.25

I'll upgrade to a newer Docker engine and test.

**Comment by joedwards32** [comment] 2023-11-04 08:57
Working for me with: Docker version 24.0.7

**Comment by daiser** [comment] 2023-11-04 09:01
This is my docker-compose.yaml

```
version: "3.8"

networks:
  app:
    external: false

services:
  app:
    image: joedwards32/cs2:latest
    environment:
      - STEAMUSER=anonymous
      - CS2_SERVERNAME=Cheetah
      - CS2_LAN=1
      - CS2_RCONPW=xxx
      - CS2_PW=yyy
      - CS2_GAMEALIAS=competitive
      - CS2_BOT_DIFFICULTY=4
      - CS2_BOT_QUOTA=10
      - CS2_BOT_QUOTA_MODE=fill
    restart: no 
    volumes:
      - /mnt/fast/static/steam2:/home/steam/cs2-dedicated/
    networks:
      - app
    ports:
      - 27014:27015
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 8G
```

**Comment by sumia01** [comment] 2023-11-04 15:30
I'm using
Docker engine : 24.0.7
OS: Ubuntu 22.04.3 LTS (Linux version 5.15.0-88-generic (buildd@lcy02-amd64-058) (gcc (Ubuntu 11.4.0-1ubuntu1~22.04) )

I tried to play with memory limit / remove limitation at all without any success.
The only difference I see is the kernel version, maybe I'll try to update it.

**Comment by sumia01** [comment] 2023-11-04 16:37
same result with Linux 6.4.0-060400-generic x86_64 :( 

Any idea?

**Comment by daiser** [comment] 2023-11-05 07:22
It's might be a CS2 bug.
Docker image works with CS2_LAN=0.

Then I tried to run server on bare OS.
Works with `+sv_lan 1`  command line argument.
Crashes with segfault when `sv_lan` set to 1 in server.cfg.

```
crash_20231105121438_25.dmp[254676]: Uploading dump (out-of-process)
/tmp/dumps/crash_20231105121438_25.dmp
crash_20231105121438_25.dmp[254676]: Finished uploading minidump (out-of-process): success = no
crash_20231105121438_25.dmp[254676]: error: libcurl.so: cannot open shared object file: No such file or directory
crash_20231105121438_25.dmp[254676]: file ''/tmp/dumps/crash_20231105121438_25.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
Segmentation fault (core dumped)
```

I think there is should be no difference. But it is.

**Comment by sumia01** [comment] 2023-11-05 09:37
After a long debugging session I ran out of ideas.
Then I tried a different image (https://github.com/Soren90/cs2-docker).
This one uses a different base image (FROM registry.gitlab.steamos.cloud/steamrt/sniper/platform ) 
and it's working flawlessly. I hope this info helps you with some future debugging.

**Comment by joedwards32** [comment] 2023-11-05 21:06
> It's might be a CS2 bug. Docker image works with CS2_LAN=0.
> 
> Then I tried to run server on bare OS. Works with `+sv_lan 1` command line argument. Crashes with segfault when `sv_lan` set to 1 in server.cfg.
> 
> ```
> Host activate: Loading (de_mirage)
> SV:  ServerSteamID=[A:1:3728032777:24598] (90177643880989705).
> Engine2PreBreakpadDumpFunction
> Engine2PreBreakpadDumpFunction: Building comment.
> Engine2PreBreakpadDumpFunction: Embedding comment.
> Engine2PreBreakpadDumpFunction: Signaling demo recorder of crash.
> Engine2PreBreakpadDumpFunction: Signaling hltv recorder of crash.
> Engine2PreBreakpadDumpFunction: Finished.
> crash_20231105123843_25.dmp[256691]: Uploading dump (out-of-process)
> /tmp/dumps/crash_20231105123843_25.dmp
> crash_20231105123843_25.dmp[256691]: Finished uploading minidump (out-of-process): success = no
> crash_20231105123843_25.dmp[256691]: error: libcurl.so: cannot open shared object file: No such file or directory
> crash_20231105123843_25.dmp[256691]: file ''/tmp/dumps/crash_20231105123843_25.dmp'', upload no: ''libcurl.so: cannot open shared object file: No such file or directory''
> Segmentation fault (core dumped)
> ```

Thanks for testing this!

I can reproduce based on the above. I'll get a fix in shortly.

**Closed** 2023-11-05 21:11 UTC
Labels: bug

**Comment by joedwards32** [comment] 2023-11-05 21:14
I'm now passing in `+sv_lan` as a CLI argument rather than defining it in server.cfg.

I've confirmed that CS2 crashes when `sv_lan` is present in server.cfg when running CS2 outside of the container in a normal Linux environment.

From my testing it isn't clear that `+sv_lan [1/0]` really does anything, which would be a CS2 bug, but the segfaults are gone.
