### ISSUE TITLE
Docker Compose help

### ISSUE THREAD

**Issue by brad0001** [joedwards32/CS2#107] opened 2024-04-05 18:01 UTC
Hey i have configured the docker compose and deploying using portainer.

I receive the error below:

I expect this docker image should install CS to the below directories? Or am i wrong? new to this kind of thing but learning as i go along! appreciate the help.

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
Error! App '730' state is 0x202 after update job.
cp: cannot create regular file '/home/steam/cs2-dedicated/game/csgo/cfg/server.cfg': No such file or directory
sed: can't read /home/steam/cs2-dedicated/game/csgo/cfg/server.cfg: No such file or directory
entry.sh: line 71: cd: /home/steam/cs2-dedicated/game/bin/linuxsteamrt64: No such file or directory
pre-hook: noop
Starting CS2 Dedicated Server
entry.sh: line 104: ./cs2: No such file or directory
post-hook: noop

Memory is fine!

root@bradserver / # df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           6.3G  1.1M  6.3G   1% /run
/dev/md2        9.8G  6.4G  2.9G  69% /
tmpfs            32G     0   32G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/md1       1005M  255M  700M  27% /boot
/dev/md4        449G   35G  392G   9% /home
/dev/md3        5.0G   68M  4.9G   2% /tmp
tmpfs           6.3G     0  6.3G   0% /run/user/0
overlay         9.8G  6.4G  2.9G  69% /var/lib/docker/overlay2/1de4506c67d85ba7ecdae3c34f2451b7a7e3c03ed4564b89af8ef0760982dc9f/merged

**Comment by brad0001** [comment] 2024-04-05 18:02
Full pastebin here: https://pastebin.com/CC7bUBDy

Really would appreciate the help guys! banging my head :)

**Comment by brad0001** [comment] 2024-04-05 18:19
root@bradserver /home # docker run -d --name=cs2 -e SRCDS_TOKEN=552F39806FC92A7EF834536085279DD9 -v $(pwd)/cs2-data:/home/steam/cs2-dedicated/ -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2
++ pwd
+ docker run -d --name=cs2 -e SRCDS_TOKEN=fdsfds -v /home/cs2-data:/home/steam/cs2-dedicated/ -p 27015:27015/tcp -p 27015:27015/udp -p 27020:27020/tcp joedwards32/cs2
cd01d1c60a2448db81adf21177b5f339b924a2aa2aefde59a1ea917eb0500a52





Interesting, the above worked. What retrospective changes do i need to make in my compose file for this to work?

**Comment by CM2Walki** [comment] 2024-04-05 20:10
Duplicate of #101

You didn't paste your `docker-compose` file, but the error indicates the container ran out of disk space:
```
Error! App '730' state is 0x202 after update job.
```

Double check that you define the bind mount from your `docker run` command: `-v /home/cs2-data:/home/steam/cs2-dedicated` in your `docker-compose` file.

**Comment by brad0001** [comment] 2024-04-05 20:22
Apologies should of wrote back!
Yes I didn't use the persistent mount when launching it and it was complaining.

Appreciate it.

**Closed** 2024-04-09 08:00 UTC
Labels: question
